# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            utilizing the ballmer peak
tagline:
url:              http://bstil22.github.io
paginate:         1
baseurl:          /
author:
  name:           Brady
  url:            https://twitter.com/brady_stilwell
  email:          bstil22@gmail.com

# Custom vars
version:          1.0.0
github:
repo:           https://github.com/poole/poole
excerpt_separator: ""
